name: alarm
description: A simple Flutter alarm manager plugin for both iOS and Android.
version: 5.2.1
homepage: https://github.com/gdelataillade/alarm

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  collection: ^1.19.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_fgbg: ^0.7.1
  json_annotation: ^4.11.0
  logging: ^1.3.0
  plugin_platform_interface: ^2.1.8
  rxdart: ^0.28.0
  shared_preferences: ^2.5.4

dev_dependencies:
  build_runner: ^2.11.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  json_serializable: ^6.13.0
  pigeon: ^26.1.7

flutter:
  assets:
    - assets/long_blank.mp3
    - assets/not_blank.mp3

  plugin:
    platforms:
      android:
        package: com.gdelataillade.alarm.alarm
        pluginClass: AlarmPlugin
      ios:
        pluginClass: SwiftAlarmPlugin

import_sorter:
  emojis: true

scripts:
  reinstall:
    (description): Cleans and reinstalls the Flutter project by removing old builds, regenerate boiler-plate codes
    (scripts):
      - flutter clean
      - flutter packages get
      - $bootstrap

  bootstrap:
    (description): Initializes the project by generating necessary code, sorting imports, applying fixes, and formatting.
    (scripts):
      - flutter pub get
      - $generate
      - $format

  generate:
    (description): Runs code generation builders and sorts imports to set up project files.
    (scripts):
      - dart run pigeon --input pigeons/alarm_api.dart
      - dart run build_runner build --delete-conflicting-outputs

  format:
    (description): Applies automated fixes, sorts imports, and formats the codebase to ensure consistent code quality.
    (scripts):
      - dart fix --apply
      - dart format --line-length 120 .
      - dart run import_sorter:main

  hard:
    (description): Forces an upgrade of Flutter and its packages to their latest versions and updates CocoaPods
    (scripts):
      - flutter upgrade --force
      - flutter packages upgrade --major-versions --tighten
